on: push
jobs:
  testing-action:
    runs-on: ubuntu-22.04
    steps:
      - uses: .github/actions/hello-docker
        id: hello
        with:
          who-to-greet: "Worldd"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
          echo $HELLO